#!/usr/bin/env python3
"""Verify and search cyclic two-fiber conference certificates.

For ``s = 2*k*k + 1``, let ``A`` be the symmetric circulant matrix with
zero diagonal generated by ``a``, and let ``C`` be the circulant sign matrix
generated by ``c``.  If

    sum(a) = 2*k,  sum(c) = 1,  and  A A^T + C C^T = (2*s-1) I,

then

    S = [[A, C], [C^T, -A]]

is a symmetric conference signing of order ``2*s`` with the desired
two-fiber quotient.  The embedded k=1,2,3 certificates are checked using
exact integer arithmetic.  The optional CP-SAT search is exploratory until
its returned candidate passes the same exact verifier.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np


CERTIFICATES: Dict[int, Dict[str, List[int]]] = {
    1: {
        "a": [0, 1, 1],
        "c": [1, 1, -1],
    },
    2: {
        "a": [0, 1, 1, 1, -1, -1, 1, 1, 1],
        "c": [1, 1, 1, -1, 1, -1, -1, 1, -1],
    },
    3: {
        "a": [0, 1, 1, 1, 1, -1, 1, -1, -1, 1,
              1, -1, -1, 1, -1, 1, 1, 1, 1],
        "c": [1, 1, 1, 1, -1, 1, -1, 1, -1, -1,
              -1, 1, 1, 1, -1, -1, 1, -1, -1],
    },
}


def circulant(first_row: Sequence[int]) -> np.ndarray:
    row = np.asarray(first_row, dtype=np.int64)
    return np.vstack([np.roll(row, shift) for shift in range(len(row))])


def periodic_autocorrelation(row: Sequence[int]) -> List[int]:
    vec = np.asarray(row, dtype=np.int64)
    return [int(vec @ np.roll(vec, shift)) for shift in range(len(vec))]


def negative_set(row: Sequence[int]) -> List[int]:
    return [index for index, value in enumerate(row) if value == -1]


def difference_counts(block: Sequence[int], modulus: int) -> List[int]:
    counts = [0] * modulus
    for left in block:
        for right in block:
            counts[(left - right) % modulus] += 1
    return counts


def verify(k: int, a: Sequence[int], c: Sequence[int]) -> Dict[str, object]:
    s = 2 * k * k + 1
    q = 2 * s - 1
    if len(a) != s or len(c) != s:
        raise AssertionError("certificate has the wrong length")
    if a[0] != 0 or any(value not in (-1, 1) for value in a[1:]):
        raise AssertionError("a must have one zero followed by signs")
    if any(value not in (-1, 1) for value in c):
        raise AssertionError("c must be a sign sequence")
    if any(a[index] != a[-index] for index in range(1, s)):
        raise AssertionError("a is not symmetric")
    if sum(a) != 2 * k or sum(c) != 1:
        raise AssertionError("row sums do not give the target quotient")

    matrix_a = circulant(a)
    matrix_c = circulant(c)
    identity_s = np.eye(s, dtype=np.int64)
    if not np.array_equal(
        matrix_a @ matrix_a.T + matrix_c @ matrix_c.T,
        q * identity_s,
    ):
        raise AssertionError("complementary autocorrelation identity failed")

    conference = np.block(
        [[matrix_a, matrix_c], [matrix_c.T, -matrix_a]]
    )
    identity_n = np.eye(2 * s, dtype=np.int64)
    if not np.array_equal(conference @ conference.T, q * identity_n):
        raise AssertionError("conference identity failed")
    if not np.array_equal(conference, conference.T):
        raise AssertionError("conference matrix is not symmetric")
    if np.any(np.diag(conference)) or not np.all(
        np.isin(conference[~np.eye(2 * s, dtype=bool)], [-1, 1])
    ):
        raise AssertionError("conference signing alphabet failed")

    p_set = negative_set(a)
    q_set = negative_set(c)
    p_counts = difference_counts(p_set, s)
    q_counts = difference_counts(q_set, s)
    for shift in range(1, s):
        required = k * k - k
        if p_counts[shift] + q_counts[shift] + int(shift in p_set) != required:
            raise AssertionError("self-indexed ASDS identity failed")

    return {
        "k": k,
        "s": s,
        "conference_order": 2 * s,
        "conference_multiplier": q,
        "a": list(a),
        "c": list(c),
        "a_autocorrelation": periodic_autocorrelation(a),
        "c_autocorrelation": periodic_autocorrelation(c),
        "P": p_set,
        "Q": q_set,
        "self_indexed_asds": {
            "P_size": len(p_set),
            "Q_size": len(q_set),
            "identity": "N_P(h)+N_Q(h)+1_P(h)=k^2-k for every h!=0",
            "verified": True,
        },
        "matrix_identities": {
            "AA_t_plus_CC_t": f"{q} I_{s}",
            "conference_square": f"S^2={q} I_{2*s}",
            "verified_exact_integer_arithmetic": True,
        },
    }


def search_cp_sat(k: int, time_limit: float) -> Tuple[str, Optional[List[int]], Optional[List[int]]]:
    """Search the cyclic equations.  A found assignment is reverified exactly."""
    try:
        from ortools.sat.python import cp_model
    except ImportError as error:  # pragma: no cover - environment dependent
        raise RuntimeError("OR-Tools is required for --search") from error

    s = 2 * k * k + 1
    model = cp_model.CpModel()
    # Boolean 1 means matrix entry +1.  A[0] is the distinguished zero.
    a_half = [model.NewBoolVar(f"a_{index}") for index in range(1, (s + 1) // 2)]
    c_bits = [model.NewBoolVar(f"c_{index}") for index in range(s)]
    model.Add(sum(a_half) == (k * k + k) // 2)
    model.Add(sum(c_bits) == (s + 1) // 2)

    def a_bit(index: int):
        index %= s
        if index == 0:
            return None
        return a_half[min(index, s - index) - 1]

    def equality_indicator(left, right, name: str):
        same = model.NewBoolVar(name)
        # same <=> left == right.
        model.Add(left == right).OnlyEnforceIf(same)
        model.Add(left != right).OnlyEnforceIf(same.Not())
        return same

    # It suffices to impose shifts 1,...,(s-1)/2 by symmetry.
    for shift in range(1, (s + 1) // 2):
        a_products = []
        c_products = []
        for index in range(s):
            left_a, right_a = a_bit(index), a_bit(index + shift)
            if left_a is not None and right_a is not None:
                a_products.append(
                    equality_indicator(left_a, right_a, f"aeq_{shift}_{index}")
                )
            c_products.append(
                equality_indicator(
                    c_bits[index], c_bits[(index + shift) % s],
                    f"ceq_{shift}_{index}",
                )
            )
        # A product is 2*same-1; the two omitted A terms contain its zero.
        # corr_A + corr_C = 0 is therefore
        # 2(sum same_A + sum same_C) - ((s-2)+s) = 0.
        model.Add(sum(a_products) + sum(c_products) == s - 1)

    solver = cp_model.CpSolver()
    solver.parameters.max_time_in_seconds = time_limit
    solver.parameters.num_search_workers = 8
    status = solver.Solve(model)
    status_name = solver.StatusName(status)
    if status not in (cp_model.OPTIMAL, cp_model.FEASIBLE):
        return status_name, None, None
    a = [0] + [-1] * (s - 1)
    for index in range(1, (s + 1) // 2):
        value = 1 if solver.Value(a_half[index - 1]) else -1
        a[index] = a[-index] = value
    c = [1 if solver.Value(bit) else -1 for bit in c_bits]
    verify(k, a, c)
    return status_name, a, c


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--search", type=int, metavar="K")
    parser.add_argument("--time-limit", type=float, default=300.0)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    results = [verify(k, data["a"], data["c"]) for k, data in sorted(CERTIFICATES.items())]
    payload: Dict[str, object] = {
        "schema": "quadratic-signing-two-fiber-cyclic-conference-v1",
        "classification": (
            "proved finite certificates by exact integer verification; no infinite-family claim"
        ),
        "embedded_certificates": results,
    }
    if args.search is not None:
        status, a, c = search_cp_sat(args.search, args.time_limit)
        search_result: Dict[str, object] = {
            "k": args.search,
            "status": status,
            "time_limit_seconds": args.time_limit,
        }
        if a is not None and c is not None:
            search_result["certificate"] = verify(args.search, a, c)
            search_result["classification"] = "exact finite certificate"
        else:
            search_result["classification"] = "solver outcome only; not a nonexistence result"
        payload["search_result"] = search_result

    rendered = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered)
    else:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
