#!/usr/bin/env python3
"""Audit subgroup-signature partitions on the finite A8/A9 walls.

Every projective spin is represented by a bit mask in F_2^(n-1), with the
first spin fixed to +1.  We enumerate subgroups generated by projective ground
states and verify the subgroup averaging identity exactly.
"""

from itertools import combinations

import numpy as np

from check_response_dual_r16 import A8, A9, energies, qnorm, spins


QMIN = {1: 0, 2: 2, 3: 6, 4: 8, 5: 8, 6: 10, 7: 18, 8: 20, 9: 24}


def spin_to_mask(z):
    return sum((int(z[i]) < 0) << (i - 1) for i in range(1, len(z)))


def mask_to_spin(mask, n):
    return np.array((1,) + tuple(-1 if (mask >> j) & 1 else 1 for j in range(n - 1)), dtype=np.int64)


def span(gens):
    values = {0}
    for g in gens:
        values |= {x ^ g for x in tuple(values)}
    return tuple(sorted(values))


def signature_partition(group, n):
    gs = [mask_to_spin(g, n) for g in group]
    cells = {}
    for i in range(n):
        sig = tuple(int(g[i]) for g in gs)
        cells.setdefault(sig, []).append(i)
    return tuple(tuple(cell) for cell in cells.values())


def split(A, cells):
    D = np.zeros_like(A)
    for cell in cells:
        D[np.ix_(cell, cell)] = A[np.ix_(cell, cell)]
    return A - D, D


def active_defect(C, D, t):
    ec = energies(C)
    ed = energies(D)
    qc = int(max(abs(ec)))
    best = -10**9
    active = 0
    for c, d in zip(ec, ed):
        for sigma in (-1, 1):
            deficit = qc - sigma * int(c)
            if deficit <= t:
                active += 1
                best = max(best, sigma * int(d) - deficit)
    return qc, best, max(-best, 0), active


def orbit_antipodal_gap(C, D, group):
    """Best opposite-cross deficit inside the G-orbit of a C ground."""
    n = len(C)
    Z = spins(n)
    ec = energies(C)
    qc = int(max(abs(ec)))
    gaps = []
    for z, c in zip(Z, ec):
        c = int(c)
        if abs(c) != qc:
            continue
        sigma = 1 if c > 0 else -1
        orbit_c = [int((z * mask_to_spin(g, n)) @ C @ (z * mask_to_spin(g, n))) for g in group]
        gap = qc + min(sigma * value for value in orbit_c)
        gaps.append(gap)
    tstar = min(gaps)
    qc2, response, gamma, _ = active_defect(C, D, tstar)
    assert qc2 == qc
    assert 2 * gamma <= tstar
    return tstar, gamma, response


def audit(A, name):
    n = len(A)
    Z = spins(n)
    EA = energies(A)
    qa = qnorm(A)
    grounds = sorted({spin_to_mask(z) for z, e in zip(Z, EA) if abs(int(e)) == qa})
    print(name, "ground projective states", len(grounds), "Q", qa)

    seen = set()
    records = []
    for rank in (1, 2, 3):
        for gens in combinations(grounds, rank):
            group = span(gens)
            if len(group) != 1 << rank or group in seen:
                continue
            seen.add(group)
            cells = signature_partition(group, n)
            C, D = split(A, cells)
            group_spins = [mask_to_spin(g, n) for g in group]
            vals = [int(z @ A @ z) for z in group_spins]
            mu_num = sum(vals)
            assert mu_num % len(group) == 0
            mu = mu_num // len(group)
            for x in group_spins:
                lhs = int(x @ D @ x)
                rhs_num = sum(int((x * g) @ A @ (x * g)) for g in group_spins)
                assert rhs_num == len(group) * lhs
                assert lhs == mu
            S = sum(qnorm(A[np.ix_(cell, cell)]) for cell in cells)
            B = sum(QMIN[len(cell)] for cell in cells)
            defects = tuple(active_defect(C, D, t)[2] for t in (0, 4, 8))
            antipodal = orbit_antipodal_gap(C, D, group)
            records.append((S - B, defects, qnorm(C), mu, tuple(sorted(map(len, cells))), tuple(vals), antipodal, group, cells))

    records.sort(key=lambda r: (-r[0], r[1], r[2]))
    print("subgroups", len(records))
    for row in records[:12]:
        print("X, Gamma(0,4,8), Q(C), mu, cells, A|G, (t*,Gamma,R), G =", row[:-1])
        print("  actual cells =", row[-1])


def main():
    audit(A8, "A8")
    audit(A9, "A9")
    print("PASS: subgroup averaging identity verified on every enumerated partition")


if __name__ == "__main__":
    main()
